max_width = 120
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
format_strings = true
comment_width = 80
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
edition = "2021"
